CREATE TABLE CUSTOMER(
       ID  INTEGER  PRIMARY KEY,
       NAME  VARCHAR2(45),
       CREDIT FLOAT
);

INSERT INTO CUSTOMER VALUES(1,'adermon1',11.5);
INSERT INTO CUSTOMER VALUES(2,'adermon2',12.5);
INSERT INTO CUSTOMER VALUES(3,'adermon3',13.5);

CREATE TABLE CUSTOMER_A(
       ID  INTEGER  PRIMARY KEY,
       NAME  VARCHAR2(45),
       CREDIT FLOAT
);

CREATE TABLE CUSTOMER_B(
       ID  INTEGER  PRIMARY KEY,
       NAME  VARCHAR2(45),
       CREDIT FLOAT
);

SELECT * FROM CUSTOMER;

SELECT * FROM CUSTOMER_A;

SELECT * FROM CUSTOMER_B;

CREATE SEQUENCE CUSTOMER_SEQ
       MINVALUE 1
       START WITH 1
       INCREMENT BY 50;
       
CREATE SEQUENCE CUSTOMERA_SEQ
       MINVALUE 1
       START WITH 1
       INCREMENT BY 50;       
       
select CUSTOMERA_SEQ.nextval from dual;       