CREATE TABLE CUSTOMER(
       ID  INTEGER  PRIMARY KEY,
       NAME  VARCHAR2(45),
       CREDIT FLOAT
);

SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER VALUES(1,'adermon1',11.5);
INSERT INTO CUSTOMER VALUES(2,'adermon2',12.5);
INSERT INTO CUSTOMER VALUES(3,'adermon3',13.5);